# =============================================================================
# pve-herc - apcupsd Slave Configuration (Network client)
# =============================================================================

apcupsd_enabled: true
apcupsd_upsname: pve-herc-ups
apcupsd_cable: ether
apcupsd_upstype: net
apcupsd_device: "192.168.1.134:3551"
apcupsd_nisip: "127.0.0.1"
apcupsd_netserver: "on"
apcupsd_polltime: 60

apcupsd_notify_enabled: true
