$ANSIBLE_VAULT;1.1;AES256
64393132333765333332306665366338316630643136326363343539623434633038653036393738
3032613738653030316332616634623562323032643166650a613539633438663565346430613462
34613339643365356134653537356161363839326565336431343962373363313262653865333363
6563643338643836630a333765346334616134396333633163623636663431643439326439356261
31653963666365656136333530393162396333353865343333623031383930643331316533393765
31656338653830616363663934386631623261633262383731383937643230616236353865353164
63383962366138633338643361373262336439343937386663303962613135356134663164343832
34346538323437306534396366353937666465326332343434656432323866653363663038353837
30653063636662373262376562373937623533313431363330623431306137323638
